"""Backend-neutral persistence protocols; no PostgreSQL implementation exists yet."""

from typing import Protocol


class AssessmentRepository(Protocol):
    def initialize(self) -> None: ...
    def schema_version(self) -> int | None: ...
    def save(self, values, *, if_absent: bool = False) -> None: ...
    def exists(self, assessment_id: str) -> bool: ...
    def get(self, assessment_id: str) -> dict | None: ...
    def list(self, scope: str, *, limit: int = 100, chronological: bool = False) -> list[dict]: ...
    def capability(self): ...
