"""Backend-neutral contracts for ingestion runtime state."""

from typing import Protocol


class ImportStorage(Protocol):
    def active_count(self) -> int: ...
    def save(self, job) -> None: ...
    def load(self, import_id: str): ...
    def delete(self, import_id: str) -> None: ...
    def cleanup(self, *, older_than_seconds=None, now=None) -> list[str]: ...


class PreparationStorage(Protocol):
    def save(self, session) -> None: ...
    def get(self, session_id: str): ...
    def latest(self): ...
    def delete(self, session_id: str) -> None: ...
    def cleanup(self, older_than_seconds, *, now=None) -> list[str]: ...
